---
title: "Comunity Design Laboratory"
subtitle: "Department of Social Work, Niigata University of Health and Welfare"
lang: en
---

The laboratory (zemi) conducts practical research focusing on community development and community-oriented care. Our main areas of study are within Niigata Prefecture and Tokyo.

Human beings are fundamentally “walking” beings. Walking stimulates physical and mental activity while also creating opportunities to connect with people and the wider community. Importantly, “walking” does not necessarily require the use of one’s own legs; rather, it refers to actively engaging with the community—such as going out into the city, strolling through parks, encountering others, or enjoying activities like walking a runway in stylish clothing. Our research aims to train QOL supporters who deliver this type of community-based care and to establish scientific evidence for its effectiveness.

In addition to the institutional and home-based care commonly found in many countries, Japan’s long-term care insurance system uniquely includes community-oriented care. In community-oriented care, it is believed that the quality of life (QOL) of service users is maintained and improved by visiting various locations within the local community—such as their own homes, day care centres, local supermarkets, convenience stores, public bathhouses, and friends’ homes. Community-based care includes dementia group homes and small-scale multi-functional home care services.

In addition to undergraduate students, we welcome patients interested in studying their own diseases, students and postgraduate researchers from other universities, international scholars, and secondary school students.

## Major Upcoming Academic Activities

- June 7: 3rd “Kirameku Watashi” Fashion Show 2026 – The Power of Connection (Nagaokakyo City)
- August 29: Kumamoto Prefecture Association of Certified Care Workers
- October 30–November 1: Geospatial Information Systems Association
- November 19–21: West Pacific Rim Consortium on Healthy Aging
- December 11–12: National Conference of the Association of Certified Care Workers (Matsuyama)

## Members

- Yoshihiko Baba [ORCID](https://orcid.org/0000-0001-7034-9724): Focusing  on community-oriented care, I worked in a group home for dementia (2006 to 2012), and in a Small-scale Multi-functional Home care (2014 to 2026).

## Practice Educator Network

The network of long-term care (kaigo) practice trainers.

## Links

- [Alzheimer's Association Japan](https://www.alzheimer.or.jp/)
  - [The Japan Dementia International Exchange Platform](https://dementia-platform.jp/en/author/babayoshihiko/)
- Niigata Intractable Diseases Support Network
  - [Patient advocacy groups](https://niigata-nansen.com/atientsgroup.html)
- [Rock Steady Boxing](https://rocksteadyboxing.org/) Fighting Back Against Parkinson's Disease
  - [RSB Japan](https://www.rsbwtsjapan.com/)
    - [RSB Tokyo Instagram](https://www.instagram.com/rock_steady_boxing_tokyo/)
- Community-Based Long-term care
  - [Small Multifunctional In-home care, Niigata](https://niigata-shoukibo.com/)
  - [Small Multifunctional In-home care, Japan](https://www.shoukibo.net/)
- Niigata University
  - [Urban Planning Laboratory](https://niigata-toshikeikaku.jimdofree.com/)
  - [Matsui Lab., Architecture Program](https://matsui2014.wixsite.com/urbandesignlab)
- Keiwa College
  - [Machizukuri](https://www.keiwa-c.ac.jp/academic/liberalarts/community_development/)
- Niigata University of Health and Welfare
  - [Department of Social Welfare](https://www.nuhw.ac.jp/faculty/sw/)
- Tokyo Institute for Geriatrics and Gerontology
  - [Social Inclusion](https://www.tmghig.jp/research/en/eresearch/researchteam/vice02/team-09/b33/)
- University College London
  - [The Bartlett School of Planning ](https://www.ucl.ac.uk/bartlett/planning)