---
title: "Software"
lang: en
---

## Kaigo Statistics

- In [Medical English: How to Read Clinical Papers](https://babayoshihiko.github.io/How/), we first read actual published papers and interpret the statistics. We then reproduce the statistical analyses used in the papers using R.

## Software developemnt

I develop geospatial-related software.

- [jpdata](https://plugins.qgis.org/plugins/jpdata/): QGIS plugin to download and load various geographic data of Japan
- geojp: R package (currently submitting to CRAN) to download and load various geographic data of Japan
  - [Kaigo Map](http://babayoshihiko.shinyapps.io/Shiny_LTCI/)
    - [note article](https://note.com/tmig_inclusion/n/nca31c17b23b3)
    - [Tokyo Institute for Geriatrics and Gerontology]](https://siencenter.jp/#map)

Please check my personal [https://github.com/babayoshihiko](https://github.com/babayoshihiko) pages.

## Translations

Doing meta analysis in R

- [Original](https://doing-meta.guide/)
- [Japanese](https://babayoshihiko.github.io/Doing-Meta-Analysis-in-R-ja/) Please note that Bookdown.org version is older.

The Epidemiologist R Handbook

- [Original](https://epirhandbook.com/en/)
- [Japanese](https://epirhandbook.com/jp/index.jp.html) Translated many chapters including GIS.



