project:
  type: website
  # サイトのURLパスを正確に指定
  output-dir: _site

website:
  title: "NUHW_SW_Baba"
  # site-url を含め、最後のスラッシュまで正しく設定
  site-url: "https://babayoshihiko.github.io/NUHW_SW_Baba/"

  navbar:
    background: "#f8dfe7"
    right:
      - text: "日本語"
        href: /index.html
      - text: "English"
        href: /en/index.html

  sidebar:
    style: "docked"
    contents:
      - section: "日本語"
        contents:
          - text: "ホーム"
            href: "index.html"
          - text: "研究"
            href: "research.html"
      - section: "English"
        contents:
          - text: "Home"
            href: "en/index.html"
          - text: "Research"
            href: "en/research.html"

format:
  html:
    theme: cosmo
    toc: true