project:
  type: website

website:
  title: "NUHW_SW_Baba"
  site-url: "https://babayoshihiko.github.io/NUHW_SW_Baba/"
  repo-url: "https://github.com/babayoshihiko/NUHW_SW_Baba"
  navbar:
    background: "#f8dfe7"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
    right:
      - text: "日本語"
        href: index.qmd
      - text: "EN"
        href: en/index.qmd

format:
  html:
    theme:
      - minty
      - custom.scss
    toc: true